title: "Christian Quinones, MD"
description: "Family medicine physician | research, systems, and infrastructure"
url: "https://cjqu001.github.io"
baseurl: ""

theme: minima
markdown: kramdown

header_pages:
  - projects.md
  - publications.md
  - cv.md
  - qempire.md
